import mysql.connector
mydb=mysql.connector.connect(host="localhost",user="root",password="Preethi@12345",database="inventorycontrolmanagement")
# password is different for everyone
print(mydb.connection_id)
cur=mydb.cursor()
#t='CREATE TABLE MANUFACTURE (PRODUCT_ID INTEGER(20),PRODUCT_NAME VARCHAR(30),MANUFACTURED_COMPANY VARCHAR(30),MANUFACTURED_DATE DATE ,NEED_TO_BE_MANUFACTURED VARCHAR(30),NO_OF_ITEMS_MANUFACTURED integer(20),NO_OF_DEFECTIVE_ITEMS INTEGER(20),MANUFACTURED_AMOUNT INTEGER(20))'
#t='CREATE TABLE PURCHASE (PRODUCT_ID INT NOT NULL,PRODUCT_NAME VARCHAR(30) NOT NULL,PURCHASE_ID INT NOT NULL,PURCHASE_DATE DATE NOT NULL,PURCHASE_STORE VARCHAR(30) NOT NULL,PURCHASE_MODE VARCHAR(30) NOT NULL,PURCHASE_QUANTITY INT NOT NULL,PURCHASE_AMOUNT FLOAT NOT NULL,DEFECTIVE INT NOT NULL)'
t='CREATE TABLE SALES (PRODUCT_ID INT NOT NULL,PRODUCT_NAME VARCHAR(30) NOT NULL,SALES_QUANTITY INT NOT NULL,SALES_DATE DATE NOT NULL,SALES_AMOUNT INT NOT NULL,PROFIT_MARGIN INT NOT NULL)'
cur.execute(t)